// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLi6kIH6WFcaw2tIrdz6qreptqQZwGzpk',
    appId: '1:482096829285:web:671dde0bb324c0cd83878c',
    messagingSenderId: '482096829285',
    projectId: 'tokoderyko',
    authDomain: 'tokoderyko.firebaseapp.com',
    storageBucket: 'tokoderyko.firebasestorage.app',
    measurementId: 'G-NTHLCHXLJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3u5po0gF1mHvaCujvk1TeSLe2LGOw8O4',
    appId: '1:482096829285:android:eb904263f208058683878c',
    messagingSenderId: '482096829285',
    projectId: 'tokoderyko',
    storageBucket: 'tokoderyko.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD29g8FdiTabH0p1fICYfib-u3x7uTu92c',
    appId: '1:482096829285:ios:ca5dc501ac01efb383878c',
    messagingSenderId: '482096829285',
    projectId: 'tokoderyko',
    storageBucket: 'tokoderyko.firebasestorage.app',
    iosBundleId: 'com.example.projek3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD29g8FdiTabH0p1fICYfib-u3x7uTu92c',
    appId: '1:482096829285:ios:ca5dc501ac01efb383878c',
    messagingSenderId: '482096829285',
    projectId: 'tokoderyko',
    storageBucket: 'tokoderyko.firebasestorage.app',
    iosBundleId: 'com.example.projek3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLi6kIH6WFcaw2tIrdz6qreptqQZwGzpk',
    appId: '1:482096829285:web:48e45ae15418266b83878c',
    messagingSenderId: '482096829285',
    projectId: 'tokoderyko',
    authDomain: 'tokoderyko.firebaseapp.com',
    storageBucket: 'tokoderyko.firebasestorage.app',
    measurementId: 'G-TN5P2KCP2G',
  );
}
