// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7LjCODydxLzdWWTmaAk_sB1GP8i42FbI',
    appId: '1:107704816232:web:41baba5f86ad984c9e21dd',
    messagingSenderId: '107704816232',
    projectId: 'tokoderyko-7dffe',
    authDomain: 'tokoderyko-7dffe.firebaseapp.com',
    storageBucket: 'tokoderyko-7dffe.firebasestorage.app',
    measurementId: 'G-ZJ5TSF4NZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB26harJYjai6rp521XcxgZETuF2BgAEZM',
    appId: '1:107704816232:android:7650e84482bf7f4a9e21dd',
    messagingSenderId: '107704816232',
    projectId: 'tokoderyko-7dffe',
    storageBucket: 'tokoderyko-7dffe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcQhswKMvQ6u3n4KV9lpVazwZe4qQMEuI',
    appId: '1:107704816232:ios:c41d911ec5f335fd9e21dd',
    messagingSenderId: '107704816232',
    projectId: 'tokoderyko-7dffe',
    storageBucket: 'tokoderyko-7dffe.firebasestorage.app',
    iosBundleId: 'com.example.projek3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcQhswKMvQ6u3n4KV9lpVazwZe4qQMEuI',
    appId: '1:107704816232:ios:c41d911ec5f335fd9e21dd',
    messagingSenderId: '107704816232',
    projectId: 'tokoderyko-7dffe',
    storageBucket: 'tokoderyko-7dffe.firebasestorage.app',
    iosBundleId: 'com.example.projek3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7LjCODydxLzdWWTmaAk_sB1GP8i42FbI',
    appId: '1:107704816232:web:40c388bfbc6814db9e21dd',
    messagingSenderId: '107704816232',
    projectId: 'tokoderyko-7dffe',
    authDomain: 'tokoderyko-7dffe.firebaseapp.com',
    storageBucket: 'tokoderyko-7dffe.firebasestorage.app',
    measurementId: 'G-02S8PZBV7M',
  );

}